"""Adicionar base CEDIS

Revision ID: 01c5b441cd24
Revises: 25007bc0e986
Create Date: 2026-08-20 16:48:37.543095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c5b441cd24'
down_revision: Union[str, Sequence[str], None] = '25007bc0e986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cedis_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_cedis_files_id'), 'cedis_files', ['id'], unique=False)
    op.create_index(op.f('ix_cedis_files_is_active'), 'cedis_files', ['is_active'], unique=False)
    op.create_index(op.f('ix_cedis_files_uploaded_by_id'), 'cedis_files', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cedis_files_uploaded_by_id'), table_name='cedis_files')
    op.drop_index(op.f('ix_cedis_files_is_active'), table_name='cedis_files')
    op.drop_index(op.f('ix_cedis_files_id'), table_name='cedis_files')
    op.drop_table('cedis_files')
    # ### end Alembic commands ###
