"""create calendar files and daily reports

Revision ID: 25007bc0e986
Revises: 07f04a1eac3d
Create Date: 2026-07-31 08:52:11.934054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25007bc0e986'
down_revision: Union[str, Sequence[str], None] = '07f04a1eac3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_calendar_files_calendar_date'), 'calendar_files', ['calendar_date'], unique=False)
    op.create_index(op.f('ix_calendar_files_id'), 'calendar_files', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_files_uploaded_by_id'), 'calendar_files', ['uploaded_by_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_daily_reports_calendar_date'), 'daily_reports', ['calendar_date'], unique=False)
    op.create_index(op.f('ix_daily_reports_created_by_id'), 'daily_reports', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_created_by_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_calendar_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_calendar_files_uploaded_by_id'), table_name='calendar_files')
    op.drop_index(op.f('ix_calendar_files_id'), table_name='calendar_files')
    op.drop_index(op.f('ix_calendar_files_calendar_date'), table_name='calendar_files')
    op.drop_table('calendar_files')
    # ### end Alembic commands ###
